%% Loads the SNR data in a specific order so that it can easily be transferred to an excel sheet

%path to the folder containing the folder of SNR data
localDataPath = setLocalDataPath(1);
input = localDataPath.BBData;


%%
subject=   {'02', '13', '15',  '20', '21', '12','17', '05', '06', '07', '18', '19'};                      

%Channels to be tested
%Put the channels from each subject into different rows.
channel = ... 
 {["LG6", "LG7", "LG8", "LB6", "LB7", "LB8", "LC2" ...
    "LC6", "LC7", "LT6", "LT7", "LT8", "LT9", ...
    "LOC6", "LOC7", "LOC8", "LOC1", "LOC2", "LOC3", "LOC4", "LOC5",...
    "LT2", "LT3", "LT4", "LT5"],... 
    ["RLS1", "RLS2", "RLI1", "RLI2","RLI3","RLI4","RLI5","RLI6","RLM4", "RLM5", "RLM8","RLM9","RLM10",...
    "RT1", "RT2", "RT3", "RT4", "RT5", "RT6", "ROI6", "ROI7", ...
    "RPI1", "RPI2", "RPI3", "ROI1", "ROI2", "ROI5", "RPM1","RPM2","RPM3","RPM4",...
    "RPM5","RPM6","RPM7","RPM8","RPM9", "RPS1", "RPS2", "RPS3", "RPS4", "RPS5",...
    "RLS5","RLS6","RLS7","RLS8","RLS9","RLS10","RPM12","RPM13","RPM14","RPI6","RPI7"],...
    ["RPO1","RPO2","RPO3","RPO4","RPO5","RPA1","RPA2","RPA3","RPA4","RPA5",...
    "RT3","RT5","RT10", "RPS1", "RPS2"],...
    ["LC5","LC6","LT2","LT3","LT4","LT5","LT7","LOC6","LOC7","LOC8","LOC9",...
"LOC12", "LOC13","LD1", "LD2", "LD3", "LD4", "LD5", "LD6","LOC1", "LOC2", "LOC3"]...
["LQ8","LQ9","LT5","LT6","LT7","LT8","LOT1","LOT2","LOT3","LOT4","LOT5","LPO4",...
"LPO5","LPO6", "LPO3", "LPO2", "LPO1"]...
["RT1","RT2","RT3", "RT4", "RT5", "RD6", "RD7", "RD8"],...
["RBC6","RBC7", "LOC1", "LOC2", "LOC3", "LOC4", "LOC5", "LOC6", "LOC7", "LOC8"],...
    ["ROC3", "ROC4", "ROC5","ROC6", "ROC7", "ROC8", "ROC9", "ROC10", "ROC11",...
    "ROC12","RC4","RC5", "RC6", "RC7", "RC8","RPS3", "RPS4", "RPS5","RPS6"],...
    ["LOC6","LOC7","LOC8","LOC9", "LT1", "LT2", "LT3", "LT4","LT5", ...
    "LB11", "LB7", "LB8", "RD10", "ROC1", "ROC2", "ROC3", "ROC4", "ROC5","ROC7", ...
    "ROC8", "ROC9", "ROC10", "ROC11"],...
    ["ROC1", "ROC2", "ROC3", "ROC4", "ROC5","ROC7", "ROC8", "ROC9", "ROC10", "ROC11",...
    "ROC12", "ROC13", "RC7","RB7", "RB8", "RB9", "RB10", "RB11","RB12"],...
    ["LOc1", "LOc2", "LOc3", "LOc4", "LOc5", "LOc6","LOc7", "LOc8", "LOc9",...
    "LSL1", "LSL2","LSL3","LSL4","LSL5", "LSL6","LSL7","LSL8",...
    "LSL9", "LSL10","LSL11","LSL12","LT2","LT3","LT4","LT5",...
    "LT1","LT6", "LB6", "LB7", "LT7","LT8","LT9","LT10","LT11", "LT12","LT13"],...
    ["LOC1", "LOC2", "LOC3","LOC4", "LOC5", "LB6", "LB7", "LOC6","LOC7","LOC8",...
    "LOC9","LOC10","LOC11","LOC12"]};
    
   %%
    
   %Loads the already calculated and saves SNR data (all channels within the subject)
   fprintf("Loading SNR Data...")
   for i=1:length(subject)
        % Load NSR data
        Path_SNR = fullfile(input,'SNR', ['sub-' subject{i}],...
        ['SNR_' 'sub-' subject{i}]);
        
        Path_allChannels = fullfile(input,'Mbb_Norm_PerRun', ['sub-' subject{i}],...
        ['sub-' subject{i} '_normalizedMbb' desc_label '_ieeg.mat']);
    
        SNR_all{i} = load(Path_SNR);
        
        all_channels_array{i} = load(Path_allChannels, 'all_channels');
   end
   fprintf("Everything has loaded.")


   %Saves only the requested channels in the order that they are requestedc
   for i=1:length(subject)
        
       all_channels = all_channels_array{i};
       SNRchannels = SNR_all{:,i};

       subChannel = channel{i};

       for j = 1:length(subChannel)
        % States which channel it is currently processing
        currentchannel = subChannel{:,j};;
        
        %finds the current channel
        channelidx = find(ismember([all_channels.all_channels.name],currentchannel));
           
        %finds SNR of the given channel
        SNR(j, i) = SNRchannels.all_chan_snr(channelidx);
    
       end
   end



